version: 2.1
executors:
  net-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk
jobs:
  tests:

    executor: net-executor
    steps:
      - checkout
      - run: |
          dotnet test --logger 'trx;LogFileName=TestResults.trx'
      - store_test_results:
          path: rpg-v2_tests/TestResults/TestResults.trx

  build-mac:

    executor: net-executor
    steps:
      - checkout
      - run: |
          dotnet publish --framework net6.0 --runtime osx-x64 --self-contained -c Release

  build-win:

    executor: net-executor
    steps:
      - checkout
      - run: |
          dotnet --version
      - run: |
          dotnet publish --framework net6.0 --runtime win-x64 --self-contained -c Release
  

  build-linux:

    executor: net-executor
    steps:
      - checkout
      - run: |
          dotnet publish --framework net6.0 --runtime linux-x64 --self-contained -c Release 

workflows:
  my-custom-workflow:
    jobs:
      - tests
      - build-mac
      - build-win
      - build-linux