version: 2.1
executors:
  net-executor6:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk

  net-executor3:
    docker:
      - image : mcr.microsoft.com/dotnet/sdk:3.1-bullseye

jobs:
  tests:

    executor: net-executor6
    steps:
      - checkout
      - run: |
          dotnet test --logger 'trx;LogFileName=TestResults.trx'
      - store_test_results:
          path: rpg-v2_tests/TestResults/TestResults.trx

  build-mac:

    executor: net-executor3
    steps:
      - checkout
      - run: |
          dotnet publish --framework net6.0 --runtime osx-x64 --self-contained -c Release rpg-v2/rpg-v2.csproj

  build-win:

    executor: net-executor3
    steps:
      - checkout
      - run: |
          dotnet publish --framework net6.0 --runtime win-x64 --self-contained -c Release rpg-v2/rpg-v2.csproj
  

  build-linux:

    executor: net-executor3
    steps:
      - checkout
      - run: |
          dotnet publish --framework net6.0 --runtime linux-x64 --self-contained -c Release rpg-v2/rpg-v2.csproj

workflows:
  my-custom-workflow:
    jobs:
      - tests
      - build-mac
      - build-win
      - build-linux