version: 2.1
executors:
  net-executor6:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk

  net-executor3:
    docker:
      - image : mcr.microsoft.com/dotnet/sdk:3.1-bullseye
    working_directory: /projects/rpg-v2

jobs:
  tests:

    executor: net-executor6
    steps:
      - checkout
      - run: |
          dotnet test --logger 'trx;LogFileName=TestResults.trx'
      - store_test_results:
          path: rpg-v2_tests/TestResults/TestResults.trx

  build-mac:

    executor: net-executor3
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: |
          wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - run : |
          dpkg -i packages-microsoft-prod.deb
      - run : |
          apt-get update; \
          apt-get install -y apt-transport-https && \
          apt-get update && \
          apt-get install -y dotnet-sdk-6.0
      - run: |
          dotnet publish --framework net6.0 --runtime osx-x64 --self-contained -c Release -o workspace/mac-output rpg-v2/rpg-v2.csproj
      - persist_to_workspace:
          root: workspace
          paths:
            - mac-output


  build-win:

    executor: net-executor3
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: |
          wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - run : |
          dpkg -i packages-microsoft-prod.deb
      - run : |
          apt-get update; \
          apt-get install -y apt-transport-https && \
          apt-get update && \
          apt-get install -y dotnet-sdk-6.0
      - run: |
          dotnet publish --framework net6.0 --runtime win-x64 --self-contained -c Release -o workspace/mac-output rpg-v2/rpg-v2.csproj
      - persist_to_workspace:
          root: workspace
          paths:
            - win-output

  build-linux:

    executor: net-executor3
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: |
          wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - run : |
          dpkg -i packages-microsoft-prod.deb
      - run : |
          apt-get update; \
          apt-get install -y apt-transport-https && \
          apt-get update && \
          apt-get install -y dotnet-sdk-6.0
      - run: |
          dotnet publish --framework net6.0 --runtime linux-x64 --self-contained -c Release -o workspace/mac-output rpg-v2/rpg-v2.csproj
      - persist_to_workspace:
          root: workspace
          paths:
            - win-output
  zip-publish:

    executor: net-executor3
    steps:
      - attach_workspace:
          at: /projects/rpg-v2
      - run: |
          ls

workflows:
  release-workflow:
    jobs:
      - tests
      - build-mac:
          requires:
            - tests
      - build-linux:
          requires:
            - tests
      - build-win:
          requires:
            - tests
      - zip-publish:
          requires:
            - build-mac
            - build-win
            - build-linux