version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
jobs:
  tests:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # dotnet test
      - store_test_results:
          path: ./

workflows:
  my-custom-workflow:
    jobs:
      - tests