version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk
jobs:
  tests:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          dotnet test -l trx
      - store_test_results:
          path: rpg-v2_tests/TestResults

workflows:
  my-custom-workflow:
    jobs:
      - tests